### ISSUE TITLE
Sorting of Atom Feed

### ISSUE THREAD

**Issue by jcsrb** [nationalarchives/ds-caselaw-public-ui#304]
while looking at the atom feed I noticed the default sort is `-date`

https://github.com/nationalarchives/ds-caselaw-public-ui/blob/d2a0bdd909ac0b05605c91d409bdc3ddb4259054/judgments/feeds.py#L76

my understanding is that  `date` refers to `published` which is unexpected when older documents are entered into the system because they are at the end of the feed rather the beginning 

<details>
  <summary>Example entry </summary>

```xml
<entry>
    <title>STEVEN MLUNDIRA v SECRETARY OF STATE FOR THE HOME DEPARTMENT</title>
    <link href="https://caselaw.nationalarchives.gov.uk/ewhc/scco/2022/1609" rel="alternate"></link>
    <published>2022-02-11T00:00:00+00:00</published>
    <updated>2022-07-08T15:24:44+00:00</updated>
    <author>
      <name>HM Courts and Tribunals Service</name>
    </author>
    <id>https://caselaw.nationalarchives.gov.uk/ewhc/scco/2022/1609</id>
    <summary type="html"></summary>
    <tna:uri>ewhc/scco/2022/1609</tna:uri>
    <tna:contenthash>ef8454df690ce3cf0114fbaad15269cfddaf6ecae0b225849c548f45d9a94c12</tna:contenthash>
  </entry>
```
</details>

in the default sorting this entry is on page 3 of the ewhc/scco subfeed because the published date is 11th Feb 2022, but it was entered in the system at a later point - my guess is it was added 8th of July 2022
 
https://caselaw.nationalarchives.gov.uk/ewhc/scco/atom.xml?page=3 

trying to sort the feed by `updated` 
https://caselaw.nationalarchives.gov.uk/ewhc/scco/atom.xml?order=-updated 
leads to an empty feed

will order by `-updated` be supported as an option? as it would help users of the API to know when a  document was added to the system or updated to an improved version

**Comment by jcsrb** [comment]
@dragon-dxw as you are a recent contributor to this project, I ask you was there/will there be any consideration of this? If not who do I need to ping ?

**Comment by jcsrb** [comment]
I would expect all sort option from the marklogic config (date, updated, transformation) to be supported

https://github.com/nationalarchives/ds-caselaw-marklogic/blob/a96eefafa9be63e0146647a37b277aee4f64888f/src/main/ml-modules/root/judgments/search/search-v2.xqy#L125-L149

We are currently using `transformation` as a sort option, but it is not clear how it is different from `updated`.
My best guess is `transformation` refers to the initial ingest into marklogic as transformation from other document types occurs, where `updated` could refer to updated happening later in the document lifecycle, such as improved metadata extraction. 

Offering sort by `-updated` would help data consumers stay on top of updated documents without having to query numerous endpoints

**Comment by dragon-dxw** [comment]
Terribly sorry about the delay!

`-updated` had a bug which we have since fixed; that should now work correctly.

`date` is the date on which the judgment was handed down; this might, for example, be back in 2000 for older judgment. It directly corresponds to the `akn:FRBRWork/akn:FRBRdate/@date` path in the XML (specifically, *any* such date; there is an outstanding issue with documents with annexes having multiple dates; we will probably correct this to be the first / one in the main document metadata)
`updated` is the time when our database records any change of the document. I believe we discovered that it updates for a large number of internal reasons (e.g. database reindexing) and we do not recommend using it. It does not correspond to an event in the XML; it is the 'last-modified' property in the MarkLogic metadata.
`transformation` is our currently recommended date for people wanting a complete index; this is when the XML document was created from the Word document; it is typically several minutes after the word document was uploaded by a clerk. It is possible that in the future we may reparse some documents; we may need to consider adding a date that preserves this information.
akn:akomaNtoso/akn:judgment/akn:meta/akn:identification/akn:FRBRManifestation/akn:FRBRdate[@name='transform']/@date path in the XML.

For far too much detail about our current search queries, you could read [the xquery](https://github.com/nationalarchives/ds-caselaw-marklogic/blob/main/src/main/ml-modules/root/judgments/search/search-v2.xqy) (but this is likely to be too much information)

Closing as I believe we've fixed this -- let us know if not!
